name: Build and Release Docker Images

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v4

      - name: Checkout Latest Code
        uses: actions/checkout@v4
        with:
          repository: qkqpttgf/OneManager-php
          path: OneManager-php

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Release Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            zhullyb/onemanager-php:latest
            zhullyb/onemanager-php:${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=zhullyb/onemanager-php:latest
          cache-to: type=inline,dest=zhullyb/onemanager-php:latest